### ISSUE TITLE
неверная текущая директория не позволяет построить путь до картинок в linux

### ISSUE THREAD

**Issue by cucumberian** [B1nC0D3/severyanochka_landing#1]
src="/static/img/main/products/milk.png"
заменить на 
src="./static/img/main/products/milk.png"

**Comment by cucumberian** [comment]
до некоторых картинок стоит абсолютный путь: src="/static/img/main/products/sausages.png"

**Comment by B1nC0D3** [comment]
fixed by OP
https://github.com/B1nC0D3/severyanochka_landing/pull/2
